weaponSkill = argument0;

var point1 = instance_create(159,112,obj_point_collision);
point1.stat = "S"
point1.number = 1
point1.weapon = weaponSkill
var point2 = instance_create(197,112,obj_point_collision);
point2.stat = "S"
point2.number = 2
point2.weapon = weaponSkill
var point3 = instance_create(299,112,obj_point_collision);
point3.stat = "S"
point3.number = 3
point3.weapon = weaponSkill
var point4 = instance_create(336,112,obj_point_collision);
point4.stat = "S"
point4.number = 4
point4.weapon = weaponSkill

var point5 = instance_create(159,180,obj_point_collision);
point5.stat = "A"
point5.number = 1
point5.weapon = weaponSkill
var point6 = instance_create(197,180,obj_point_collision);
point6.stat = "A"
point6.number = 2
point6.weapon = weaponSkill
var point7 = instance_create(298,180,obj_point_collision);
point7.stat = "A"
point7.number = 3
point7.weapon = weaponSkill
var point8 = instance_create(336,180,obj_point_collision);
point8.stat = "A"
point8.number = 4
point8.weapon = weaponSkill

var point9 = instance_create(159,244,obj_point_collision);
point9.stat = "I"
point9.number = 1
point9.weapon = weaponSkill
var point10 = instance_create(197,244,obj_point_collision);
point10.stat = "I"
point10.number = 2
point10.weapon = weaponSkill
var point11 = instance_create(298,244,obj_point_collision);
point11.stat = "I"
point11.number = 3
point11.weapon = weaponSkill
var point12 = instance_create(336,244,obj_point_collision);
point12.stat = "I"
point12.number = 4
point12.weapon = weaponSkill
